config/routes.rb
Rails.application.routes.draw do
  resources :provider_clinics
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/provider_clinic.rb
class ProviderClinic < ApplicationRecord
  UPPER_TIERS = %i{A B C}.freeze

  # I encapsulated the knowledge of tiers and zipcodes to PartnerClinic scopes + a constant.
  # That way, if we have to repeat or change this logic elsewhere in the code there is
  # one place we have to change (Single Responsibility Principle). I would also make
  # sure that there is a compound index on tier and zipcode on PartnerClinic, in order to
  # improve the performance of each individual query and both queries together.
  # The performance of IN clauses however is non-determinstic even with indices,
  # so I would keep an eye on this query and consider how to
  # make it better given the current amount of data, how often it changes, and the query goals.
  scope :upper_tiers, -> { where(tier: UPPER_TIERS) }
  scope :in_zipcodes, -> (zipcodes) { where(zipcode: zipcodes) }

  # Queries for provider clinics in a set of given zipcodes, and then sorts those clinics by their tier first and then the distance of that zipcode.
  # If two clinics are in the same tier, it orders the closest one first.
  # I would definitely leave a comment on a method like to make what it is doing as clear as possible.
  #
  # @param zipcodes_by_distance [Hash] a dictionary of zipcodes and their distance in decimals
  # @return [Array<ProviderClinic>]
  def self.by_tier_and_distance(zipcodes_by_distance = {})
    raise "Please provide a hash of zipcodes and their distances from a location" if zipcodes_by_distance.empty?

    nearby_zipcodes = zipcodes_by_distance.keys
    nearby_clinics = self.upper_tiers.in_zipcodes(nearby_zipcodes)

    clinics_by_distance = nearby_clinics.map do |clinic|
      {
        clinic: clinic,
        zipcode: clinic.zipcode,
        distance: zipcodes_by_distance[clinic.zipcode],
        tier: clinic.tier
      }
    end

    # Try to name variables as semantically as possible to help future
    # developers understand what the code is doing. Also use the wonderful
    # built-in Enumerable methods Ruby gives us to write the sort more
    # cleanly instead of using the confusing nested `while` loop.
    # Make use of .map instead of mutation arrays and hashes in place.
    clinics_by_distance.sort{|a, b| [a[:tier], a[:distance]] <=> [b[:tier], b[:distance]] }.map{|d| d[:clinic]}
  end
end

app/models/serializable_provider_clinic.rb
class SerializableProviderClinic < JSONAPI::Serializable::Resource
  attributes :tier, :zipcode
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/provider_clinics_controller.rb
# frozen_string_literal: true

class ProviderClinicsController < ApplicationController
  DEFAULT_CLINIC_RADIUS = 20
  deserializable_resource :provider_clinic

  # GET /provider_clinics or /provider_clinics.json
  def index
    return render status: 422 if params[:zipcode].nil?

    nearby_clinics = ProviderClinic.by_tier_and_distance(zipcodes_by_distance)
    # Another part of this refactor includes abstracting away serialization.
    # This is now handled via jsonapi-rails with the SerializableProviderClinic class.
    render jsonapi: nearby_clinics, status: :ok
  end

  private

  def zipcodes_by_distance
    radius = params[:radius] || DEFAULT_CLINIC_RADIUS
    nearby_zipcodes = ZipcodeAPI::Client.zipcodes_within_radius(params[:zipcode], radius)
    Hash[nearby_zipcodes.map { |z| [z['zip_code'], z['distance']] }]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/provider_clinics_helper.rb
module ProviderClinicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProviderClinicApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/provider_clinics/_form.html.erb
<%= form_with(model: provider_clinic) do |form| %>
  <% if provider_clinic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(provider_clinic.errors.count, "error") %> prohibited this provider_clinic from being saved:</h2>

      <ul>
        <% provider_clinic.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :zipcode %>
    <%= form.text_field :zipcode %>
  </div>

  <div class="field">
    <%= form.label :radius %>
    <%= form.number_field :radius %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/provider_clinics/edit.html.erb
<h1>Editing Provider Clinic</h1>

<%= render 'form', provider_clinic: @provider_clinic %>

<%= link_to 'Show', @provider_clinic %> |
<%= link_to 'Back', provider_clinics_path %>

app/views/provider_clinics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Provider Clinics</h1>

<table>
  <thead>
    <tr>
      <th>Zipcode</th>
      <th>Radius</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @provider_clinics.each do |provider_clinic| %>
      <tr>
        <td><%= provider_clinic.zipcode %></td>
        <td><%= provider_clinic.radius %></td>
        <td><%= link_to 'Show', provider_clinic %></td>
        <td><%= link_to 'Edit', edit_provider_clinic_path(provider_clinic) %></td>
        <td><%= link_to 'Destroy', provider_clinic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Provider Clinic', new_provider_clinic_path %>

app/views/provider_clinics/new.html.erb
<h1>New Provider Clinic</h1>

<%= render 'form', provider_clinic: @provider_clinic %>

<%= link_to 'Back', provider_clinics_path %>

app/views/provider_clinics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Zipcode:</strong>
  <%= @provider_clinic.zipcode %>
</p>

<p>
  <strong>Radius:</strong>
  <%= @provider_clinic.radius %>
</p>

<%= link_to 'Edit', edit_provider_clinic_path(@provider_clinic) %> |
<%= link_to 'Back', provider_clinics_path %>